import { Product, ModelData, NavLink } from './types';

export const LOGO_URL = 'https://i.imgur.com/3Z6E5od.png';

export const products: Product[] = [
  { id: 1, name: 'Meteorit', price: 5000.0, imageUrl: 'https://picsum.photos/seed/meteorite/400/400' },
  { id: 2, name: 'Tshirt', price: 500.0, imageUrl: 'https://picsum.photos/seed/tshirt/400/400' },
  { id: 3, name: 'Astronot Filtre Kahve Kağıdı Tutacağı', price: 250.0, imageUrl: 'https://picsum.photos/seed/astronaut/400/400', tag: 'EL YAPIMI' },
  { id: 4, name: 'Termos', price: 5000.0, imageUrl: 'https://picsum.photos/seed/thermos/400/400' },
  { id: 5, name: 'NFT TASARIMLAR', price: 5000.0, imageUrl: 'https://picsum.photos/seed/nft/400/400' },
];

export const primaryNavLinks: NavLink[] = [
  { label: 'TURKSAT-6A', path: '/turksat-6a' },
  { label: 'TURKSAT-5B', path: '/turksat-5b' },
  { label: 'TURKSAT-5A', path: '/turksat-5a' },
  { label: 'TURKSAT-4A', path: '/turksat-4a' },
  { label: 'TURKSAT-3B', path: '/turksat-3b' },
  { label: 'TURKSAT-3A', path: '/turksat-3a' },
  { label: 'TURKSAT-2A', path: '/turksat-2a' },
  { label: 'TURKSAT-1C', path: '/turksat-1c' },
  { label: 'TURKSAT-1B', path: '/turksat-1b' },
  { label: 'TURKSAT-1A', path: '/turksat-1a' },
  { label: 'GOKTURK-2', path: '/gokturk-2' },
  { label: 'GOKTURK-1', path: '/gokturk-1' },
  { label: 'RASAT', path: '/rasat' },
  { label: 'IMECE', path: '/imece' },
  { label: 'LAGARI', path: '/lagari' },
  { label: 'ISS', path: '/iss' },
  { label: 'ALBAMAN-3D', path: '/albaman-3d' },
  { label: 'ALBAMEN-3B', path: '/albamen-3b' },
  { label: 'ALBAMEN-LARA', path: '/albamen-lara' },
  { label: 'MERCURY', path: '/mercury' },
  { label: 'VENUS', path: '/venus' },
  { label: 'EARTH', path: '/earth' },
  { label: 'MARS', path: '/mars' },
  { label: 'JUPITER', path: '/jupiter' },
  { label: 'SATURN', path: '/saturn' },
  { label: 'URAN', path: '/uranus' },
  { label: 'NEPTUNE', path: '/neptune' },
  { label: 'SPUTNIK', path: '/sputnik' },
  { label: 'VOYAGER1', path: '/voyager1' },
  { label: 'VOYAGER2', path: '/voyager2' },
  { label: 'HUBBLE', path: '/hubble' },
  { label: 'JAMESWEBB', path: '/jameswebb' },
  { label: 'KEPLER', path: '/kepler' },
  { label: 'EXOMARS', path: '/exomars' },
  { label: 'MARSODYSSEY', path: '/marsodyssey' },
  { label: 'MARS RECONNAISSANCE', path: '/marsreconnaissance' },
  { label: 'PERSEVERANCE', path: '/perseverance' },
  { label: 'CURIOSITY', path: '/curiosity' },
  { label: 'INGENUITY', path: '/ingenuity' },
  { label: 'OPPORTUNITY', path: '/opportunity' },
  { label: 'SOJOURNER', path: '/sojourner' },
  { label: 'SPIRIT', path: '/spirit' },
  { label: 'ZHURONG', path: '/zhurong' },
  { label: 'VIKING1', path: '/viking1' },
  { label: 'PATHFINDER', path: '/pathfinder' },
  { label: 'VIKING2', path: '/viking2' },
  { label: 'INSIGHT', path: '/insight' },
  { label: 'ANASAYFA', path: '/' },
];

export const secondaryNavLinks: NavLink[] = [
  { label: 'HAKKIMIZDA', path: '/hakkimizda' },
  { label: 'HİZMETLER', path: '/hizmetler' },
  { label: 'SHOP', path: '/shop' },
  { label: 'BLOG', path: '/blog' },
  { label: 'BASINDA BİZ', path: '/basinda-biz' },
  { label: 'GALERİ', path: '/galeri' },
  { label: 'İLETİŞİM', path: '/iletisim' },
  { label: 'DFS', path: '/dfs' },
];

const GITHUB_REPO_URL = 'https://raw.githubusercontent.com/StingerUA/AlbaSpace/main/';

export const modelData: Record<string, ModelData> = {
  'gokturk-1': {
    title: 'Göktürk-1',
    description: 'Göktürk-1 is a high resolution optical Earth observation satellite designed and developed for the Turkish Ministry of National Defence.',
    images: ['https://picsum.photos/seed/gokturk1_1/800/600', 'https://picsum.photos/seed/gokturk1_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Gokturk-1.glb`,
  },
  'gokturk-2': {
    title: 'Göktürk-2',
    description: 'Göktürk-2 is a high resolution Earth observation satellite designed and developed by TÜBİTAK and Turkish Aerospace Industries.',
    images: ['https://picsum.photos/seed/gokturk2_1/800/600', 'https://picsum.photos/seed/gokturk2_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Gokturk-2.glb`,
  },
  rasat: {
    title: 'RASAT',
    description: 'RASAT is an Earth observation satellite designed and developed by TÜBİTAK Space Technologies Research Institute.',
    images: ['https://picsum.photos/seed/rasat_1/800/600', 'https://picsum.photos/seed/rasat_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Rasat.glb`,
  },
  imece: {
    title: 'İmece',
    description: 'İmece is a sub-meter resolution Earth observation satellite project of Turkey.',
    images: ['https://picsum.photos/seed/imece_1/800/600', 'https://picsum.photos/seed/imece_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Imece.glb`,
  },
  'turksat-1a': {
    title: 'Türksat 1A',
    description: "Türksat 1A was Turkey's first communications satellite. It was lost during launch in January 1994 due to a third stage failure.",
    images: [
      'https://space.skyrocket.de/img_sat/turksat-1b__1.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/e/e4/Ariane_4_V60_launch_with_Turksat_1A_1994-01-24.jpg',
    ],
    glbUrl: `${GITHUB_REPO_URL}Turksat_1A.glb`,
  },
  'turksat-1b': {
    title: 'Türksat 1B',
    description: 'Türksat 1B was successfully launched in 1994 to deliver communications capacity for Turkey.',
    images: ['https://picsum.photos/seed/turksat1b/800/600', 'https://picsum.photos/seed/turksat1b2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_1B.glb`,
  },
  'turksat-1c': {
    title: 'Türksat 1C',
    description: 'Türksat 1C launched in 1996 and continued expanding the nation’s communications network.',
    images: ['https://picsum.photos/seed/turksat1c/800/600', 'https://picsum.photos/seed/turksat1c2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_1C.glb`,
  },
  'turksat-2a': {
    title: 'Türksat 2A',
    description: 'Türksat 2A was launched in 2001 to provide additional broadcast and data services.',
    images: ['https://picsum.photos/seed/turksat2a/800/600', 'https://picsum.photos/seed/turksat2a2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_2A.glb`,
  },
  'turksat-3a': {
    title: 'Türksat 3A',
    description: 'Türksat 3A is a communications satellite operated by Turksat.',
    images: ['https://picsum.photos/seed/turksat3a/800/600', 'https://picsum.photos/seed/turksat3a2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_3A.glb`,
  },
  'turksat-3b': {
    title: 'Türksat 3B',
    description: 'Türksat 3B expands data coverage with Ka-band capacity.',
    images: ['https://picsum.photos/seed/turksat3b/800/600', 'https://picsum.photos/seed/turksat3b2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_3B.glb`,
  },
  'turksat-4a': {
    title: 'Türksat 4A',
    description: 'Türksat 4A is a communications satellite operated by Turksat.',
    images: ['https://picsum.photos/seed/turksat4a/800/600', 'https://picsum.photos/seed/turksat4a2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_4A.glb`,
  },
  'turksat-5a': {
    title: 'Türksat 5A',
    description: 'Türksat 5A entered service in 2021, adding new broadcast and broadband capacity.',
    images: ['https://picsum.photos/seed/turksat5a/800/600', 'https://picsum.photos/seed/turksat5a2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_5A.glb`,
  },
  'turksat-5b': {
    title: 'Türksat 5B',
    description: 'Türksat 5B is a high-throughput satellite launched in 2021.',
    images: ['https://picsum.photos/seed/turksat5b/800/600', 'https://picsum.photos/seed/turksat5b2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_5B.glb`,
  },
  'turksat-6a': {
    title: 'Türksat 6A',
    description: "Türksat 6A is Turkey's first domestically produced communications satellite project.",
    images: ['https://picsum.photos/seed/turksat6a/800/600', 'https://picsum.photos/seed/turksat6a2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Turksat_6A.glb`,
  },
  lagari: {
    title: 'Lagari',
    description: 'Lagari is a technology demonstration microsatellite concept.',
    images: ['https://picsum.photos/seed/lagari/800/600', 'https://picsum.photos/seed/lagari2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Lagari.glb`,
  },
  iss: {
    title: 'International Space Station',
    description: 'The International Space Station is a modular space station in low Earth orbit.',
    images: ['https://picsum.photos/seed/iss_1/800/600', 'https://picsum.photos/seed/iss_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}International_Space_Station_.glb`,
  },
  'albaman-3d': {
    title: 'Albaman 3D',
    description: 'Albaman is a stylized AlbaSpace character model presented in 3D.',
    images: ['https://picsum.photos/seed/albaman3d/800/600', 'https://picsum.photos/seed/albaman3d2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Albaman_3D.glb`,
  },
  'albamen-3b': {
    title: 'Albamen 3B',
    description: 'Alternate Albamen pose rendered as a 3D asset.',
    images: ['https://picsum.photos/seed/albamen3b/800/600', 'https://picsum.photos/seed/albamen3b2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Albamen_3B.glb`,
  },
  'albamen-lara': {
    title: 'Albamen Lara',
    description: 'Albamen Lara variant highlighting another character style.',
    images: ['https://picsum.photos/seed/albamenlara/800/600', 'https://picsum.photos/seed/albamenlara2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Albamen_Lara.glb`,
  },
  mercury: {
    title: 'Mercury',
    description: 'Mercury is the smallest planet in the Solar System and nearest to the Sun.',
    images: ['https://picsum.photos/seed/mercury_1/800/600', 'https://picsum.photos/seed/mercury_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Mercury.glb`,
  },
  venus: {
    title: 'Venus',
    description: 'Venus is the second planet from the Sun, named after the Roman goddess of love and beauty.',
    images: ['https://picsum.photos/seed/venus_1/800/600', 'https://picsum.photos/seed/venus_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Venus.glb`,
  },
  earth: {
    title: 'Earth',
    description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life.',
    images: ['https://picsum.photos/seed/earth_1/800/600', 'https://picsum.photos/seed/earth_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Earth.glb`,
  },
  mars: {
    title: 'Mars',
    description: 'Mars is the fourth planet from the Sun and is often called the Red Planet.',
    images: ['https://picsum.photos/seed/mars_1/800/600', 'https://picsum.photos/seed/mars_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Mars.glb`,
  },
  jupiter: {
    title: 'Jupiter',
    description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System.',
    images: ['https://picsum.photos/seed/jupiter_1/800/600', 'https://picsum.photos/seed/jupiter_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Jupiter.glb`,
  },
  saturn: {
    title: 'Saturn',
    description: 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System.',
    images: ['https://picsum.photos/seed/saturn_1/800/600', 'https://picsum.photos/seed/saturn_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Saturn.glb`,
  },
  uranus: {
    title: 'Uranus',
    description: 'Uranus is the seventh planet from the Sun with a unique sideways rotation.',
    images: ['https://picsum.photos/seed/uranus_1/800/600', 'https://picsum.photos/seed/uranus_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Uranus.glb`,
  },
  neptune: {
    title: 'Neptune',
    description: 'Neptune is the eighth and farthest-known Solar planet from the Sun.',
    images: ['https://picsum.photos/seed/neptune_1/800/600', 'https://picsum.photos/seed/neptune_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Neptune.glb`,
  },
  sputnik: {
    title: 'Sputnik 1',
    description: 'Sputnik 1 was the first artificial Earth satellite launched in 1957.',
    images: ['https://picsum.photos/seed/sputnik_1/800/600', 'https://picsum.photos/seed/sputnik_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Sputnik.glb`,
  },
  voyager1: {
    title: 'Voyager 1',
    description: 'Voyager 1 is a space probe launched by NASA on September 5, 1977.',
    images: ['https://picsum.photos/seed/voyager1_1/800/600', 'https://picsum.photos/seed/voyager1_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Voyager.glb`,
  },
  voyager2: {
    title: 'Voyager 2',
    description: 'Voyager 2 launched on August 20, 1977, to study the outer planets.',
    images: ['https://picsum.photos/seed/voyager2_1/800/600', 'https://picsum.photos/seed/voyager2_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Voyager.glb`,
  },
  hubble: {
    title: 'Hubble Space Telescope',
    description: 'The Hubble Space Telescope was launched into low Earth orbit in 1990.',
    images: ['https://picsum.photos/seed/hubble_1/800/600', 'https://picsum.photos/seed/hubble_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Hubble.glb`,
  },
  jameswebb: {
    title: 'James Webb Space Telescope',
    description: 'The James Webb Space Telescope is designed primarily to conduct infrared astronomy.',
    images: ['https://picsum.photos/seed/jameswebb_1/800/600', 'https://picsum.photos/seed/jameswebb_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}James_Webb.glb`,
  },
  kepler: {
    title: 'Kepler Space Telescope',
    description: 'The Kepler space telescope was launched to discover Earth-size planets around other stars.',
    images: ['https://picsum.photos/seed/kepler_1/800/600', 'https://picsum.photos/seed/kepler_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Kepler.glb`,
  },
  exomars: {
    title: 'ExoMars',
    description: 'ExoMars is a joint astrobiology programme by ESA and Roscosmos.',
    images: ['https://picsum.photos/seed/exomars_1/800/600', 'https://picsum.photos/seed/exomars_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}ExoMars.glb`,
  },
  marsodyssey: {
    title: 'Mars Odyssey',
    description: '2001 Mars Odyssey is a robotic spacecraft orbiting the planet Mars.',
    images: ['https://picsum.photos/seed/marsodyssey_1/800/600', 'https://picsum.photos/seed/marsodyssey_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Mars_Odyssey.glb`,
  },
  marsreconnaissance: {
    title: 'Mars Reconnaissance Orbiter',
    description: 'The Mars Reconnaissance Orbiter conducts reconnaissance and exploration of Mars from orbit.',
    images: ['https://picsum.photos/seed/mro_1/800/600', 'https://picsum.photos/seed/mro_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Mars_Reconnaissance.glb`,
  },
  perseverance: {
    title: 'Perseverance Rover',
    description: 'Perseverance is a car-sized Mars rover designed to explore Jezero crater.',
    images: ['https://picsum.photos/seed/perseverance_1/800/600', 'https://picsum.photos/seed/perseverance_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Perseverance.glb`,
  },
  curiosity: {
    title: 'Curiosity Rover',
    description: 'Curiosity is a car-sized Mars rover exploring Gale crater as part of NASA’s Mars Science Laboratory mission.',
    images: ['https://picsum.photos/seed/curiosity_1/800/600', 'https://picsum.photos/seed/curiosity_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Curiosity.glb`,
  },
  ingenuity: {
    title: 'Ingenuity Helicopter',
    description: 'Ingenuity is a small robotic helicopter operating on Mars as part of the Mars 2020 mission.',
    images: ['https://picsum.photos/seed/ingenuity_1/800/600', 'https://picsum.photos/seed/ingenuity_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Ingenuity.glb`,
  },
  opportunity: {
    title: 'Opportunity Rover',
    description: 'Opportunity was a Mars rover active from 2004 to 2018.',
    images: ['https://picsum.photos/seed/opportunity_1/800/600', 'https://picsum.photos/seed/opportunity_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Opportunity.glb`,
  },
  sojourner: {
    title: 'Sojourner Rover',
    description: 'Sojourner was the first rover to operate on Mars during the Mars Pathfinder mission.',
    images: ['https://picsum.photos/seed/sojourner_1/800/600', 'https://picsum.photos/seed/sojourner_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Sojourner.glb`,
  },
  spirit: {
    title: 'Spirit Rover',
    description: 'Spirit was a Mars rover in NASA’s Mars Exploration Rover mission.',
    images: ['https://picsum.photos/seed/spirit_1/800/600', 'https://picsum.photos/seed/spirit_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Spirit.glb`,
  },
  zhurong: {
    title: 'Zhurong Rover',
    description: 'Zhurong is a Chinese Mars rover that is part of the Tianwen-1 mission.',
    images: ['https://picsum.photos/seed/zhurong_1/800/600', 'https://picsum.photos/seed/zhurong_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Zhurong.glb`,
  },
  viking1: {
    title: 'Viking 1',
    description: 'Viking 1 was the first spacecraft to successfully land on Mars and perform its mission.',
    images: ['https://picsum.photos/seed/viking1_1/800/600', 'https://picsum.photos/seed/viking1_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Viking_1.glb`,
  },
  pathfinder: {
    title: 'Mars Pathfinder',
    description: 'Mars Pathfinder delivered the Sojourner rover and demonstrated low-cost lander technologies.',
    images: ['https://picsum.photos/seed/pathfinder_1/800/600', 'https://picsum.photos/seed/pathfinder_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Pathfinder.glb`,
  },
  viking2: {
    title: 'Viking 2',
    description: 'Viking 2 landed on Mars in 1976, complementing the Viking 1 mission.',
    images: ['https://picsum.photos/seed/viking2_1/800/600', 'https://picsum.photos/seed/viking2_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Viking_2.glb`,
  },
  insight: {
    title: 'InSight Lander',
    description: 'InSight studied the deep interior of Mars from its landing site in Elysium Planitia.',
    images: ['https://picsum.photos/seed/insight_1/800/600', 'https://picsum.photos/seed/insight_2/800/600'],
    glbUrl: `${GITHUB_REPO_URL}Insight.glb`,
  },
};
